dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
  - TERM=dumb
language: java
#jdk: openjdk8
jdk: openjdk11
install: true
script:
### JDK11 ###
- echo run projects uses java 11...
### JDK8 ###
- jdk_switcher use oraclejdk8 || echo cannot execute jdk_switcher use oraclejdk8 command
- echo run projects uses java 1.8
- ./mvnw clean test -U
cache:
  pip: true
  packages: true
  directories:
  - ~/.m2
