dist: trusty
notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
  - TERM=dumb
language: java
#jdk: openjdk8
jdk: openjdk11
#python: 3
install: true
#addons:
#  apt:
#    update: true
#    packages:
#      - python3-dev
#      - python3-pip
#      - python3-six
#      - python3-setuptools
#      - libxml2-utils
#      - unzip
#      - sudo
#      - lsof
#      - wget
#      - bash
#      - curl
#      - jq
#before_install:
#  # pip -> httpie / docker-compose
#  - which pip3    || echo 'which pip3 command failed.'
#  - export PATH=$HOME/.local/bin:$PATH
#  - pip3 install --user $(whoami) --upgrade pip # not pip3
#  - which pip3    || echo 'which pip3 command failed.'
#  - pip3 install --user $(whoami) --upgrade httpie
#  - http --version --debug
#  # custom scripts -> wait_for $portNumber} / stop_any ${port1} ${port2} ...
#  - source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
#  - stop_any 80 8080 5432 5672 27017
script:
### JDK11 ###
- echo run projects uses java 11...
#
### JDK8 ###
- jdk_switcher use oraclejdk8 || echo cannot execute jdk_switcher use oraclejdk8 command
#
- echo run projects uses java 1.8
- ./mvnw clean test
cache:
  pip: true
  packages: true
  directories:
  - ~/.m2
